# About titanic dataset

- As you know the tragic accident happened that day several innocent lost there life in the mid of the night actually in pitch black night
- It was horroble to imagine the situation there 
- Here in this dataset we have the passengers data who travelled by titanic that day
- This dataset contains many important imformation regarding survivers and dead ones

#### Initializing libraries that have to use in the dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df2 = pd.read_csv('test.csv')
df = pd.read_csv('train.csv')
df3 = pd.read_csv('gender_submission.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

##### Here we have 891 rows and 12 columns in the train dataset of the titanic

In [3]:
df.shape

(891, 12)

### All the columns details

`Col`

- PassengerId -> Every passengers has unique id
- Survived -> 0 denoted who died and 1 for who survived and it is binary denotion
- Pclass -> Pclass is the class they booked to live in the titanic here are 3 classes 1 > 2 > 3 class and it is ordinal 
- Name -> Name of the passenger
- Sex -> Gender of the passenger
- Age -> Age of the passenger
- SibSp -> siblings that of each passengers
- Parch -> parent child relation
- Ticket -> tickets number of each passengers
- Fare -> total price of the tickets 
- Cabin -> Cabin alloted to the passengers
- Embarked -> port from where the passengers boarded, labeled as: C = Cherbourg, Q = Queenstown, and S = Southampton.

`Obervation`
- Here age, cabin and embarked has null values
- All the data types are correctly assigned 
- Column distribution -
1) numerical col -> PassengerId, Age, SibSp, Parch, Fare, Pclass, Survived
2) categorial col -> Sex, embarked
3) Other col -> Name, Cabin, Ticket

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

`Observation`
- age has 177 null values, percentage = 19.86532
- cabin has 687 null values, percentage =  77.104377
- embarked has 2 null values, percentage = 0.224467

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [15]:
df['Age'].isnull().value_counts(normalize=True)*100

Age
False    80.13468
True     19.86532
Name: proportion, dtype: float64

In [17]:
df['Cabin'].isnull().value_counts(normalize=True)*100

Cabin
True     77.104377
False    22.895623
Name: proportion, dtype: float64

In [18]:
df['Embarked'].isnull().value_counts(normalize=True)*100

Embarked
False    99.775533
True      0.224467
Name: proportion, dtype: float64

### Task 3
- Task 3. Run df.describe() for numerical columns and df.describe(include='object') for categorical. Write 3 observations from each output.

`Observation`
##### for numerical col
- There nothing very much suspicious, the only thing i can is in the fare feature where min in 0 means passenger travelling free and max is huge 512.32
- price difference for different class
- Maximum travelling from 3rd class
- The correct decision is median because Age has outliers (max=80) which pull the mean up. Always use median when outliers exist.
##### for categorical col
- a lot of missing value in Cabin
- Many ticket number is same around 200 ticket numbers are same, even cabin are same of many passengers
- ticket has 7 freq means there is passenger with 7 same number ticket highest

In [19]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [21]:
df.describe(include='object')

                       Name   Sex  Ticket Cabin Embarked
count                   891   891     891   204      889
unique                  891     2     681   147        3
top     Dooley, Mr. Patrick  male  347082    G6        S
freq                      1   577       7     4      644

### Task 4
- Task 4. Handle missing Age values. First check: is the mean Age different across Pclass? Use groupby. Then fill nulls with the median Age per Pclass — not the overall median. Verify nulls are gone after filling.

`Observation`
- So its a big learning for me actually i dont how to use group function 
- We filled the null values of age with the median to its respective Pclass`s age median
- WE have used median because of outliers present in the age that shifts the mean unwantedly instead use median when outliers present

In [36]:
df['Age'] = df['Age'].fillna(df.groupby('Pclass')['Age'].transform('median'))

In [38]:
df['Age'].isnull().sum()

np.int64(0)

### Task 5
- Task 5. Handle missing Embarked (2 nulls) and Cabin (687 nulls) differently. Fill Embarked with mode. For Cabin — don't fill it. Instead create a new binary column Has_Cabin (1 if cabin exists, 0 if null). Explain why in markdown.

`Observation`
- Here first we have to fill missing value of Embarked with some value that i chosen mode to fill it with.
- Why mode because mode means most frequency so it is easy to fill it with mode because it is categorical col also
- Here we have to now make a new col Has_cabin and remove cabin col from data to make it more clear and clean

In [ ]:
df['Embarked'].fillna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,NaN
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,B28,NaN

In [45]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [49]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S